"""添加 Agent 运行记录模型

Revision ID: 942cbffd39fa
Revises: 7b9080d5e924
Create Date: 2026-06-10 10:43:32.659786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942cbffd39fa'
down_revision: Union[str, Sequence[str], None] = '7b9080d5e924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
